Login y autenticacion/SitioSimple/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from portafolio import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name='home'),
    path('blog/',include('blog.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Login y autenticacion/blog/urls.py
from django.urls import path
#from .views import render_posts
from .import views
app_name = 'blog'
urlpatterns = [
    path('',views.render_posts, name= 'posts'),
    path('<int:post_id>/', views.post_detail, name='post_detail'),
]

Login y autenticacion/blog/models.py
from django.db import models
import datetime
# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    description= models.TextField()
    image = models.ImageField(upload_to="blog/images")
    date = models.DateField(default=datetime.date.today)

    def __str__(self) -> str:
        return self.title

Login y autenticacion/blog/views.py
from django.shortcuts import render, get_list_or_404
from .models import Post

# Create your views here.
def render_posts(request):
    posts = Post.objects.all()
    return render(request, 'posts.html', {"posts":posts})

def post_detail(request, post_id):
    post = get_list_or_404(Post, pk= post_id)
    return render(request, "post_detail.htlm", {"post": post})

Login y autenticacion/blog/templates/post_detail.html
{% extends 'layout.html' %}

{% block content %}
    <div class="text-center">
        <h1>{{ post.title }}</h1>
        <h2 class="my-2 h5 text-muted">{{ post.date|date:'F jS Y' }}</h2>
        <img src="{{ post.image.url }}" alt="{{ post.title }}" class="img-fluid">
        <div class="my-4">
            {{ post.description|safe }}
        </div>
    </div>
{% endblock %}

Login y autenticacion/blog/templates/posts.html
{% extends 'layout.html' %}

{% block content %}
    <h1 class="fs-2">Post</h1>
    <h3>La cantidad {{ total_posts }} post{{ total_posts|pluralize }}</h3>

    {% for post in posts %}
        <div class="py-3">
            <div class="card card-body bg-black">
                <div class="row">
                    <div class="col-3">
                        <img class="img-fluid" src="{{ post.image.url }}" alt="{{ post.title }}">
                    </div>
                    <div class="col-9">
                        <h1>{{ post.title }}</h1>
                        <p>{{ post.description|striptags|truncatechars:100 }}</p>
                        <p>{{ post.date|date:'M d Y'|upper }}</p>
                        <a href="{% url 'blog:post_detail' post.id %}">{{ post.title }}</a>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

Login y autenticacion/portafolio/templates/home.html
{% extends 'layout.html' %}

{% block content %}
    {% load static %}

    <header class="row bg-black">
        <div class="col-md-4">
            <img src="{% static 'portfolio/profile.jpeg' %}" />
        </div>
        <div class="col-md-8 my-auto p-4">
            <h1>Soy <strong>William Morales </strong></h1>
            <h3>Estudiante de Analisis de Sistemas</h3>
            <p>
                Soy estudiante, disfruto mucho el aprender, por lo que siempre estoy realizando algún
                curso orientado al desarrollo de software, ciencia de datos e inteligencia artificial. Una persona
                con una actitud dinámica, responsable y comprometido a la hora de encarar y desarrollar nuevos
                proyectos. Me gusta asumir retos y superarme día a día.
            </p>
            <a class="btn btn-primary btn-lg rounded-0 my-3" href="{% static 'portfolio/cv.pdf' %}">Descargar CV</a>
        </div>
    </header>

    <div class="row my-4 text-center">
        <h3>Mis proyectos</h3>
        <p>Algunos que te pueden interesar</p>
        {% for project in projects %}
            <div class="col-md-4 p-4">
                <div class="card bg-black card-project">
                    <img src="{{ project.image.url }}" class="card-img-top" />
                    <div class="card-body">
                        <h2>{{ project.title }}</h2>
                        <p>{{ project.description }}</p>
                        {% if project.url %}
                            <a href="{{ project.url }}" class="btn btn-light rounded-0 btn-sm" target="__blank"
                                rel="noreferrer">Visitar el proyecto</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}